version: "3"


services:


  search_services_s5:
    container_name: springboot-search
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management UI port
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq  # Persist data across container restarts
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
